#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# load homebrew zsh-completions
fpath=(/usr/local/share/zsh-completions $fpath)

# Customize to your needs...
rbenv() {
  eval "$(command rbenv init -)"
  rbenv "$@"
}

# Show the tty-clock
alias tclock="tty-clock -s -c"

# Get the weather
alias weather='curl wttr.in/london'

setopt clobber

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Docker shortcuts
alias dcu="docker-compose up -d"
alias dcd="docker-compose down"
alias dcr="docker-compose run --rm"
alias dcrm="docker-compose rm"
alias dcb="docker-compose build"
alias docker-prune='docker system df && docker container prune && docker volume prune && docker system prune && docker system df'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

. /usr/local/opt/asdf/asdf.sh
alias lg='lazygit'
